# Generated by Django 2.1.3 on 2018-11-25 20:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('lo_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('A', 'Active'), ('D', 'Dead'), ('R', 'Retired'), ('N', 'NPC')], max_length=2)),
                ('started', models.DateTimeField(default=datetime.datetime.now)),
                ('resurrected', models.BooleanField()),
                ('excommunicated', models.BooleanField()),
                ('active', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('restricted', models.BooleanField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GuildRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restricted', models.BooleanField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Guild')),
            ],
            options={
                'ordering': ['guild__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('restricted', models.BooleanField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('restricted', models.BooleanField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. UK numbers are +44 and drop leading '0'. For example +441632962499. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('first_aider', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('next_kin_name', models.CharField(max_length=200)),
                ('next_kin_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. UK numbers are +44 and drop leading '0'. For example +441632962499. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('next_kin_relationship', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.Branch')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('restricted', models.BooleanField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='character',
            name='guilds',
            field=models.ManyToManyField(to='character.Guild'),
        ),
        migrations.AddField(
            model_name='character',
            name='languages',
            field=models.ManyToManyField(to='character.Language'),
        ),
        migrations.AddField(
            model_name='character',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Nationality'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Player'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Race'),
        ),
    ]
