# Generated by Django 2.1.3 on 2018-11-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
