# Generated by Django 2.1.3 on 2019-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='excommunicated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='resurrected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
