# Generated by Django 2.1.3 on 2018-11-25 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20181125_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='active',
        ),
    ]
