# Generated by Django 2.1.3 on 2019-02-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_auto_20190218_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='banned_races',
            field=models.ManyToManyField(blank=True, to='character.Race'),
        ),
    ]
