# Generated by Django 2.1.3 on 2019-02-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20190218_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='next_kin_name',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='next_kin_number',
            new_name='emergency_contact_number',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='next_kin_relationship',
            new_name='emergency_contact_relationship',
        ),
    ]
