# Generated by Django 2.1.3 on 2019-02-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_auto_20190218_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Nationality'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Player'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Race'),
        ),
        migrations.AddField(
            model_name='cash',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character'),
        ),
    ]
