# Generated by Django 2.1.3 on 2019-02-22 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_auto_20190222_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pennies', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('S', 'Sold Items'), ('B', 'Bought Items'), ('P', 'Mission Pay'), ('C', 'Material Cost'), ('F', 'Fine'), ('T', 'Tithe')], max_length=2)),
                ('reference', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='character.Character')),
            ],
        ),
    ]
