# Generated by Django 2.1.3 on 2019-02-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildrank',
            name='starting_rank',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='excommunicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='resurrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Dead'), ('R', 'Retired'), ('N', 'NPC')], default='A', max_length=2),
        ),
    ]
