# Generated by Django 2.1.3 on 2019-02-22 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20190222_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='id',
        ),
        migrations.AddField(
            model_name='character',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
